// Code generated by tygo. DO NOT EDIT.

//////////
// source: handlers.go

/**
 * Handlers holds shared dependencies for all API handlers.
 */
export interface Handlers {
}

//////////
// source: types.go

/**
 * ServiceStatus is the response shape for each entry in GET /api/status.
 */
export interface ServiceStatus {
  name: string;
  active: boolean;
}
/**
 * ServiceLog is the response shape for each entry in GET /api/logs.
 */
export interface ServiceLog {
  name: string;
  content: string;
}
/**
 * NotificationsResponse is the response for GET and POST /api/notifications.
 */
export interface NotificationsResponse {
  enabled: boolean;
}
/**
 * CryRequest is the request body for POST /api/cry.
 */
export interface CryRequest {
  confidence: number /* float64 */;
}
/**
 * CryResponse is the response for GET /api/cry.
 * DetectedAt is null when no cry has been recorded yet.
 */
export interface CryResponse {
  detected_at: string | null;
  seconds_ago?: number /* int */;
  confidence?: number /* float64 */;
}
/**
 * FartRequest is the request body for POST /api/fart.
 */
export interface FartRequest {
  confidence: number /* float64 */;
  wetness: number /* float64 */;
  wet: boolean;
}
/**
 * FartResponse is the response for GET /api/fart.
 * DetectedAt is null when no fart has been recorded yet.
 */
export interface FartResponse {
  detected_at: string | null;
  seconds_ago?: number /* int */;
  confidence?: number /* float64 */;
  wetness?: number /* float64 */;
  is_wet?: boolean;
}
/**
 * DetectStatusRequest is the request body for POST /api/detect-status.
 */
export interface DetectStatusRequest {
  error: string;
}
/**
 * DetectStatusResponse is the response for GET /api/detect-status.
 * Error is null when the detector is healthy.
 */
export interface DetectStatusResponse {
  error?: string;
  seconds_ago?: number /* int */;
}
